import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  imageBG: {
    flex: 1,
    flexDirection: "column",
    resizeMode: "cover",
    justifyContent: "flex-end",
  },
  formContainer: {
    backgroundColor: "#fff",
    borderRadius: 25,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  photoBox: {
    alignSelf: "center",
    marginTop: -60,
    marginBottom: 32,
    backgroundColor: "#f6f6f6",
    height: 120,
    width: 120,
    borderRadius: 16,
  },
  headerReg: {
    alignSelf: "center",
    marginBottom: 33,
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 30,
    lineHeight: 35,
    letterSpacing: 1,
    color: "#212121",
  },
  headerLogin: {
    alignSelf: "center",
    marginTop: 32,
    marginBottom: 33,
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 30,
    lineHeight: 35,
    letterSpacing: 1,
    color: "#212121",
  },
  form: {
    marginHorizontal: 32,
    marginBottom: 16,
    gap: 16,
  },
  input: {
    height: 50,
    padding: 16,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: "#f6f6f6",
    color: "#bdbdbd",
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
  },
  button: {
    height: 51,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 43,
    backgroundColor: "#ff6c00",
    borderRadius: 100,
  },
  buttonTitle: {
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    color: "#fff",
  },
  textRedirect: {
    marginBottom: 45,
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    color: "#1B4371",
  },
});
